version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - client_node_modules:/app/client/node_modules
      - server_node_modules:/app/server/node_modules
    ports:
      - "80:80"
      - "3000:3000"
      - "5173:5173"  # Vite dev server
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ski-rental
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - mongo
    command: /bin/sh -c "while sleep 1000; do :; done"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  node_modules:
  client_node_modules:
  server_node_modules:
